version: '2.2'
services:
  database-app:
    image: 'mysql:5.7'
    restart: on-failure
    volumes:
      - '/tmp/db1:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswd
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppassword
    ports:
      - '3301:3306'
  database-user:
    image: 'mysql:5.7'
    restart: on-failure
    volumes:
      - '/tmp/db2:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswd
      - MYSQL_DATABASE=user_sheme
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=userpass
    ports:
      - '3302:3306'
