---
info:
  app:
    name: App Starter Config
  developer:
    name: Ilia Podstavkov
    email: psyfabriqdev@gmail.com
spring:
  application:
    name: ${APP_NAME:app-pfq-config}

  # cloud:
  #   config:
  #     server:
  #       git:
  #         uri: https://github.com/psyfabriq/cloud-project.git

  output:
    ansi:
      enabled: always

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD:test}

server:
  port: 8888
...