---
info:
  app:
    name: Spring Enterprise Application (Happy News)
    version: 1.0.0
  developer:
    email: psyfabriqdev@gmail.com
    name: Ilia Podstavkov
spring:
  application:
    name: ${APP_NAME:app-pfq-site}
  output:
    ansi:
      enabled: always
server:
  port: 8081
security:
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw3IiR89wUvWZIBItwKAG
          TNwxfnTo1K5FqwiFmp+TO+3N9qWa4R9Z3zET2tX7bV3GkaG2wCipq4tStftUpJXj
          Wl0B3JtS59MUdFx0bItrh/nykkAZ1QNQoQjHCxo79s8YHh7IjYRoKlLO4214gME3
          9k29vDRItFOfOvqYi3fWmqBHOoVA+6wyvav9vKk1rq5OKC3A12UNSd8EJuAC7sld
          Fcxxh0ZGVmjc0EXO8EO24mnAqiAZW32ezz+Y++upp0aeZbu2R+NyTCNDik0Q6scg
          p38GySHZmolfjTdQNiu0OXEpsI2IrC2Bq6/+DimRBmBSgBS7pyWjZII85YOtBFLh
          4wIDAQAB
          -----END PUBLIC KEY-----
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}
datasource:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://${DATABASE_URI:127.0.0.1}:${DATABASE_PORT:3301}/${DATABASE_SHEMA:appdb}?useSSL=false&useUnicode=true
  schema: ${DATABASE_SHEMA:appdb}
  username: ${DATABASE_USER:appuser}
  password: ${DATABASE_PASS:apppassword}
  scan_pacage: ru.psyfabriq.enterprise
  scan_pacage_entity: ru.psyfabriq.enterprise.entity
hibernate:
  hb2ddl:
    auto: update
  jdbc:
    batch_size: '10'
    fetch_size: '50'
  max_fetch_depth: '3'
  show_sql: 'false'
...


